import Head from 'next/head';
import { Post, PostWidget, Categories } from '../components';

const posts = [
  { title: 'Pokémon song', excerpt: 'What Kind Of Pokémon Are You?' },
  { title: 'Motivation', excerpt: 'Do you want to be a Pokémon Master?' }
];
export default function Home() {
  return (
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='col-span-1 lg:col-span-8'>
          {posts.map((post) => (
            <Post key={post.title} post={post} />
          ))}
        </div>
        <div className='col-span-1 lg:col-span-4'></div>
      </main>
    </div>
  );
}
