import Head from 'next/head';
import { Post, PostWidget, Categories } from '../components';
import { getPosts } from '../services';
import { Post as PostType } from '../types';

const posts = [
  { title: 'Pokémon song', excerpt: 'What Kind Of Pokémon Are You?' },
  { title: 'Motivation', excerpt: 'Do you want to be a Pokémon Master?' }
];

type HomeProps = {
  posts: Array<{
    node: PostType;
  }>;
};

export default function Home({ posts }: HomeProps) {
  return (
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='col-span-1 lg:col-span-8'>
          {posts.map(({ node: post }) => (
            <Post key={post.title} post={post} />
          ))}
        </div>
        <div className='col-span-1 lg:col-span-4'>
          <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts }
  };
}
